### ISSUE TITLE
binder badge broken

### ISSUE THREAD

**Issue by mathematicalmichael** [plotly/jupyterlab-dash#23]
app does not render. 

```
Exception in thread Thread-104:
Traceback (most recent call last):
  File "/srv/conda/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/srv/conda/lib/python3.7/threading.py", line 1158, in run
    self.function(*self.args, **self.kwargs)
  File "/home/jovyan/jupyterlab_dash/__init__.py", line 71, in _perform_show
    """)
OSError: 
Unable to communicate with the jupyterlab-dash JupyterLab extension.
Is this Python kernel running inside JupyterLab with the jupyterlab-dash
extension installed?

You can install the extension with:

$ jupyter labextension install jupyterlab-dash

```

running that suggested command does not help.

**Comment by mathematicalmichael** [comment]
tried to run
```
!pip install jupyterlab-dash==0.1.0a2
!jupyter labextension install jupyterlab-dash@0.1.0-alpha.2
```
then restart kernel and run all.
that worked.

**Comment by sangeetsaurabh** [comment]
For me, it didn't help...

**Comment by thorwhalen** [comment]
Same here. Same problem (on Mac). Tried the above solution proposals. Still run into

`Exception in thread Thread-54:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1166, in run
    self.function(*self.args, **self.kwargs)
  File "/Users/ME/.virtualenvs/p3/lib/python3.7/site-packages/jupyterlab_dash/__init__.py", line 71, in _perform_show
    """)
OSError: 
Unable to communicate with the jupyterlab-dash JupyterLab extension.
Is this Python kernel running inside JupyterLab with the jupyterlab-dash
extension installed?

You can install the extension with:

$ jupyter labextension install jupyterlab-dash`
