### ISSUE TITLE
"jupyterlab_dash@0.1.0" is not compatible with the current JupyterLab

### ISSUE THREAD

**Issue by gusseppe** [plotly/jupyterlab-dash#6]
ValueError: 
"jupyterlab_dash@0.1.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.16.3 <0.17.0        >=0.19.1 <0.20.0 @jupyterlab/application
>=0.16.3 <0.17.0        >=0.19.2 <0.20.0 @jupyterlab/notebook
>=0.16.3 <0.17.0        >=0.19.1 <0.20.0 @jupyterlab/console

My jupyter lab --version:
0.32.1

Kind regards,

**Comment by rafaleo** [comment]
The same here: 
```
(base) C:\Users\cp\jupyterlab-dash>jupyter labextension link . --debug
Searching ['C:\\Users\\cp\\jupyterlab-dash', 'C:\\Users\\cp\\.jupyter', 'C:\\Anaconda3\\etc\\jupyter', 'C:\\ProgramData\
\jupyter'] for config files
Looking for jupyter_config in C:\ProgramData\jupyter
Looking for jupyter_config in C:\Anaconda3\etc\jupyter
Looking for jupyter_config in C:\Users\cp\.jupyter
Looking for jupyter_config in C:\Users\cp\jupyterlab-dash
> "C:\Program Files\nodejs\npm.CMD" pack C:\Users\cp\jupyterlab-dash

> jupyterlab_dash@0.1.0 prepare C:/Users/cp/jupyterlab-dash
> npm run clean && npm run build


> jupyterlab_dash@0.1.0 clean C:\Users\cp\jupyterlab-dash
> rimraf lib


> jupyterlab_dash@0.1.0 build C:\Users\cp\jupyterlab-dash
> tsc

jupyterlab_dash-0.1.0.tgz
> "C:\Program Files\nodejs\npm.CMD" pack C:\Users\cp\jupyterlab-dash

> jupyterlab_dash@0.1.0 prepare C:/Users/cp/jupyterlab-dash
> npm run clean && npm run build


> jupyterlab_dash@0.1.0 clean C:\Users\cp\jupyterlab-dash
> rimraf lib


> jupyterlab_dash@0.1.0 build C:\Users\cp\jupyterlab-dash
> tsc

jupyterlab_dash-0.1.0.tgz
Traceback (most recent call last):

  File "C:\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 71, in start
    ans = self.run_task()

  File "C:\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 119, in run_task
    for arg in self.extra_args

  File "C:\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 119, in <listcomp>
    for arg in self.extra_args

  File "C:\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 310, in link_package
    return handler.link_package(path)

  File "C:\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 584, in link_package
    return self.install_extension(path)

  File "C:\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 366, in install_extension
    info = self._install_extension(extension, tempdir)

  File "C:\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1157, in _install_extension
    raise ValueError(msg)

ValueError:
"jupyterlab_dash@0.1.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.16.3 <0.17.0        >=0.19.1 <0.20.0 @jupyterlab/application
>=0.16.3 <0.17.0        >=0.19.2 <0.20.0 @jupyterlab/notebook
>=0.16.3 <0.17.0        >=0.19.1 <0.20.0 @jupyterlab/console



Errored, use --debug for full output:
ValueError:
"jupyterlab_dash@0.1.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.16.3 <0.17.0        >=0.19.1 <0.20.0 @jupyterlab/application
>=0.16.3 <0.17.0        >=0.19.2 <0.20.0 @jupyterlab/notebook
>=0.16.3 <0.17.0        >=0.19.1 <0.20.0 @jupyterlab/console

(base) C:\Users\cp\jupyterlab-dash>
```

**Comment by KyleOS** [comment]
@gusseppe 
I ran into the same issue:

```
ValueError:
"jupyterlab_dash@0.1.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.15.4-0 <0.16.0-0    >=0.19.1-0 <0.20.0-0 @jupyterlab/application
>=0.15.4-0 <0.16.0-0    >=0.19.2-0 <0.20.0-0 @jupyterlab/notebook
>=0.15.4-0 <0.16.0-0    >=0.19.1-0 <0.20.0-0 @jupyterlab/console
```

I just re-installed the latest version of jupyterlab with:

`conda install -c conda-forge jupyterlab 
`
 and everything worked fine from there.

Hope this helps you guys.

**Comment by gusseppe** [comment]
@KyleOS Thanks a lot!. In my case, I did: pip install -U jupyterlab .

Regards,

**Comment by ANGEL1303** [comment]
I Tried to install Jupyter lab sandbox and came up this issue:
Please Help!


```
(base) C:\Users\C001>jupyter labextension install jupyterlab_sandbox
Node v10.13.0

> C:\Users\C001\Continumm\npm.CMD pack jupyterlab_sandbox
npm notice
npm notice package: jupyterlab_sandbox@0.1.0
npm notice === Tarball Contents ===
npm notice 1.2kB package.json
npm notice 460B  README.md
npm notice 1.5kB lib/index.d.ts
npm notice 6.7kB lib/index.js
npm notice 0     style/index.css
npm notice === Tarball Details ===
npm notice name:          jupyterlab_sandbox
npm notice version:       0.1.0
npm notice filename:      jupyterlab_sandbox-0.1.0.tgz
npm notice package size:  3.3 kB
npm notice unpacked size: 9.8 kB
npm notice shasum:        5e5cc37196b26f03f92d1080a37ea1926af2f096
npm notice integrity:     sha512-R+g+UkQNzHquN[...]RqZrZc4KGIlXw==
npm notice total files:   5
npm notice
jupyterlab_sandbox-0.1.0.tgz

Errored, use --debug for full output:
ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=0.15.0 <0.16.0 @jupyterlab/application
>=0.19.1 <0.20.0        >=0.15.0 <0.16.0 @jupyterlab/apputils

(base) C:\Users\C001>jupyter lab --version
0.35.4
```
